/**
 * Curated recruiter suggestions offered in the interview-experience submission
 * form.
 *
 * The list is intentionally broader than the `Company` table, because students
 * report off-campus and pool-campus interviews for recruiters the Placement
 * Cell has never created a job profile for. It is offered through a `datalist`
 * rather than a `select`, so an unlisted recruiter can still be typed in and
 * never blocks a submission — matching the free-text company decision recorded
 * in docs/DECISIONS.md (2026-09-15).
 */
export const COMPANY_OPTIONS = [
  "1Mg (Tata 1mg)",
  "7-Eleven",
  "99acres.com",
  "Aakash Educational Services Ltd.",
  "ABB",
  "Ab Inbev",
  "Abacus.Ai",
  "Abhi Bus",
  "Abnormal Ai",
  "Abnormal Security",
  "Accelya",
  "Accenture",
  "Accolite",
  "Acko",
  "Acmegrade",
  "Actian",
  "Adani Group",
  "Addepar",
  "Aditya Birla Capital",
  "Adobe",
  "Advantage Club.Ai",
  "Agilitas",
  "Agoda",
  "AiDash",
  "Airbase",
  "Airbnb",
  "Airbus",
  "Airbyte",
  "Airtel Payments Bank",
  "Airtelxlabs",
  "Aisensy26",
  "Ajio",
  "Akal Information Systems Ltd",
  "Akamai",
  "Algosec",
  "Allen Digital",
  "AlphaGrep",
  "Altimetrik",
  "Alvarez & Marsal",
  "Amadeus Labs",
  "Amazon",
  "Amber",
  "Amd",
  "Amenify",
  "American Chase",
  "American Express",
  "Amgen",
  "ANAROCK",
  "Angel One",
  "Anthropic",
  "Antino",
  "Anumana",
  "Anz",
  "Aon",
  "Apac",
  "Apiwiz",
  "Appdynamics",
  "Appinventiv",
  "Apple",
  "Applied Materials",
  "Appscrip",
  "Aptiv",
  "Arcad Software",
  "Arcana",
  "Arcesium",
  "Arctan",
  "Arista Networks",
  "Arm",
  "Armorcode",
  "Arrise",
  "Artius Systems",
  "Ascendion",
  "Aspire",
  "Aspora",
  "Assurant",
  "Astrosage",
  "Astrotalk",
  "Atain",
  "Athena Education",
  "Atlan",
  "Atlas",
  "Atlassian",
  "Atlys",
  "Au Small Finance",
  "Aumnee",
  "Autodesk",
  "Automation Anywhere",
  "Automattic",
  "Auxia",
  "Aventior",
  "Aveva",
  "Aviso Ai",
  "Avp – Digital Solutions",
  "Avtaar Skincare",
  "Avyon",
  "Axa Xl",
  "Axis Bank",
  "Axis Mutual Funds",
  "Axtria",
  "Axxela",
  "Ayu Health",
  "Bachhat",
  "Bain & Company",
  "Bajaj",
  "Baker Hughes",
  "Banao Technologies",
  "Bank Of America",
  "Barclays",
  "Barco",
  "Baya Systems",
  "Bcg",
  "Beatroute",
  "Beiersdorf",
  "Belzabar Software Design",
  "Betterplace",
  "BharatBrainz",
  "Bharatx",
  "BigBasket",
  "Bitgo",
  "Bizango",
  "Blackrock",
  "Blackstone Inc.",
  "Blink Health",
  "BlinkIn",
  "Blinkit",
  "Blinkrx",
  "Block",
  "Bloomberg",
  "Bloomreach",
  "Blue Matter",
  "Blue Origin",
  "Blue Yonder",
  "Bluestacks",
  "Bmc Softwares",
  "Bmw Techworks",
  "Bny Mellon",
  "Boeing",
  "Boldcare",
  "Booking Holdings",
  "Bosch Global Software Technologies",
  "Boston Consulting Group",
  "Boston Scientific",
  "Bountous X Accolite",
  "Bp",
  "Bpcl",
  "Brainstrom Force",
  "Branch",
  "Breathe Esg",
  "Brick&Bolt",
  "Bright Money",
  "Brightly Software",
  "Broadcom",
  "Browser Use",
  "BrowserStack",
  "BuildShip",
  "Built",
  "Bullit",
  "Buyhatke",
  "Byteridge",
  "C-DOT",
  "C2Fo",
  "C3I-Hub",
  "C5I",
  "Ca Technologies",
  "Cadence",
  "Callhq.Ai",
  "Canara Bank",
  "Canonical",
  "Capillary Technologies",
  "Capital One",
  "CarDekho",
  "Care Insurance",
  "Care.Fi",
  "Careernet",
  "Carelon Global Solutions",
  "Cargill",
  "Carnation",
  "Carousell Group",
  "Cars24",
  "Cartesia",
  "Cartier",
  "Cashfree",
  "Cbx1 - Stealth Startup",
  "Ccognitio Analytics",
  "Cent",
  "Cepheid",
  "Cgi",
  "Chalo",
  "Chargebee",
  "Chegg",
  "Chubb",
  "Ciena",
  "Cimpress",
  "Cisco",
  "Citadel",
  "Citi",
  "Citrix",
  "Clappia",
  "Clarity",
  "Clear",
  "Cleartax",
  "Cleartrip",
  "Clebal Technologies",
  "Clickpost",
  "Clinisys",
  "Cloudera",
  "Cloudflare",
  "Cloudraft",
  "Cloudsek",
  "Cnlabs",
  "Codechef",
  "Codemonk",
  "Codesnag",
  "Codespire Solutions",
  "Codess.Cafe",
  "Codgenan",
  "Codtech",
  "Coforge",
  "Cognizant",
  "Cogoport",
  "Cohesity",
  "Coinbase",
  "CoinSwitch",
  "CommerceIQ",
  "Commvault",
  "Compass",
  "Complyance",
  "Comprehend Health",
  "Concentric Ai",
  "Concentrix",
  "Concertai",
  "Condé Nast",
  "Conduent",
  "Confluent",
  "Copart",
  "Coreel Technologies",
  "Cotzero",
  "Couchbase",
  "Coupa",
  "Coupang",
  "Couture Ai",
  "CRED",
  "Credgenics",
  "Credit Karma",
  "Crossover",
  "Crowdstrike",
  "CSUEB Associated Students",
  "Curefit",
  "Cvent",
  "Cyfuture",
  "Cyware",
  "D.E. Shaw",
  "Da Vinci",
  "Daice Labs",
  "Data Annotation",
  "Databricks",
  "Datazip",
  "Dcluttr",
  "DealSense AI",
  "Deccan-Ai",
  "Decision Point Analytics",
  "Decover Ai",
  "Deel",
  "Degreed",
  "Delhivery",
  "Dell Technologies",
  "Deloitte",
  "Delta Exchange",
  "Deltax",
  "Deutsche Bank",
  "Deutsche Telekom",
  "DevRev",
  "Dezerv",
  "Dhurin",
  "Dialpad",
  "Digicert",
  "Digital Green",
  "Digital Ocean",
  "Directorate of Coordination Police Wireless",
  "Directi",
  "Disney",
  "Disprz",
  "District",
  "Docquity",
  "Docusign",
  "Dodge Ai",
  "Dolby Laboratories",
  "Domdog",
  "Domino Data Lab",
  "Domyn",
  "DP World",
  "Dream11",
  "Drishti IAS",
  "Dropbox",
  "Dsp Mutual Funds",
  "Dunzo",
  "Ea Games",
  "Early Fit",
  "Easebuzz",
  "Easemytrip",
  "Ebay",
  "Ecolab",
  "Edelweiss",
  "Edge Verve",
  "EdgeTensor",
  "Editorialist",
  "Edra Labs",
  "Eightfold",
  "Elastic",
  "Elecbits",
  "Electrochem Power Systems",
  "Electrolux Group",
  "Electronic Arts (Ea)",
  "Elevana Dev House",
  "Elevate",
  "Elite8 Digital",
  "Elythra Edufyi Tech Solutions",
  "Ema Unlimited",
  "Emergent",
  "Enphase Energy",
  "Entnt",
  "Epam",
  "Epicor",
  "Epifi",
  "Equal",
  "Equifax",
  "Ericsson",
  "Estee Advisors",
  "Ethos",
  "Eurofins",
  "Even",
  "Eversana",
  "Ex - Conjecture , AI Security Bootcamp",
  "EXL",
  "Expedia",
  "Experian",
  "Ey",
  "F5",
  "Facebook",
  "Factset",
  "Fampay",
  "Fanatics",
  "Fareportal",
  "Fast Retailing",
  "Fastenal",
  "Fi",
  "Fibe.India",
  "Fico",
  "Fidelity Investments",
  "Fieldai",
  "Finacplus",
  "FinBox",
  "Findability Sciences",
  "Finvest",
  "Firmway",
  "First Citizen",
  "Firstclub",
  "Fischer Jordan",
  "Fiserv",
  "Fission Labs",
  "Five9",
  "Fiverr",
  "Fivetran",
  "Flexcar",
  "Flexin",
  "Flexiple",
  "Flexmoney Technologies",
  "Flexport",
  "Flipkart",
  "Floqast",
  "Flow Traders",
  "Floworks",
  "Fluence",
  "Fluidcloud",
  "Fnp",
  "FNZ",
  "Ford",
  "Forsys Inc",
  "Fortanix",
  "Fourkites",
  "Fractal",
  "Franklin Templeton",
  "Freechargebizz",
  "Freespace",
  "Freshworks",
  "Fuelbuddy",
  "Fusion Cx",
  "Futures First",
  "Gainsight",
  "Galaxy.Ai",
  "Game Theory",
  "Gartner",
  "GE Vernova",
  "Ge Aerospace",
  "Ge Healthcare",
  "General Mills",
  "Genpact",
  "Gep",
  "Gigaforce",
  "Gitlab",
  "Glean",
  "Glenn",
  "Global Payments",
  "Globalfoundries",
  "Globallogic",
  "GlueX Protocol",
  "Gnani.ai",
  "Gocomet",
  "GoDaddy",
  "Godrej",
  "Gojek",
  "GoKwik",
  "Goldman Sachs",
  "Goodspace Ai",
  "Google",
  "Goquant",
  "Grab",
  "Grafana",
  "Grapevine Tal",
  "Graviton",
  "Greenway Health",
  "Greyb",
  "Greyorange",
  "Groupon",
  "Groww",
  "Guidepoint",
  "Gxs Bank",
  "H2Loop",
  "Haber",
  "HackerRank",
  "Haptik",
  "Harman",
  "Harness",
  "Harvey",
  "HashedIn",
  "Havells",
  "Hays(Salesforce)",
  "Head Field Solutions Pvt. Ltd.",
  "Headcount",
  "Headout",
  "Healthkart",
  "Heizen",
  "Here Technologies",
  "Hestabit",
  "Hevo Data",
  "HIE Agency",
  "HiEd Success",
  "Highradius",
  "Highspot",
  "Hike",
  "Hilti",
  "Hirepro",
  "Honeywell",
  "House of Edtech",
  "Housing.Com",
  "Hpe",
  "Hsbc",
  "Hubspot",
  "Hudson River Trading",
  "HugoHub",
  "Hummingbird",
  "Hyperbots",
  "Hypersonix",
  "Hyperverge",
  "IBM",
  "ICICI Bank",
  "Idfc First Bank",
  "Ikigai",
  "Imc Trading",
  "Impact Analytics",
  "Impetus",
  "Indeed",
  "Independent",
  "Indiamart",
  "Indian Standards",
  "Indigo",
  "Indihood",
  "Indiqube",
  "Indmoney",
  "Indusind Bank",
  "Infilect",
  "Info Edge",
  "Infosys",
  "Infra.Market",
  "Inmobi",
  "Innovaccer",
  "Instabase",
  "Instamart",
  "Instawork",
  "Insurity",
  "Intel",
  "Intellect Design Arena",
  "Intellectyx, Inc.",
  "Intermesh",
  "Intuit",
  "ION",
  "Iqigai",
  "Iqvia",
  "Irage",
  "Irdeto",
  "Ittiam",
  "Ixigo",
  "JPMorgan Chase",
  "Jade Global",
  "Jakson Group",
  "JDA",
  "Jfrog",
  "Jio Platforms Limited (Jpl)",
  "Jm Financial",
  "Join Talent",
  "Joveo",
  "JT Attorney Alliance",
  "Juniper",
  "Juniper Square",
  "Jupiter",
  "Juspay",
  "Jyesta",
  "K12",
  "Kaleris",
  "Kapstan",
  "Kearney",
  "Keysight Technologies",
  "Kickdrum",
  "Kimbal",
  "Kinaxis",
  "Kissflow",
  "Kivi Capital",
  "Kiwi",
  "KKR",
  "Kla",
  "Kodnest",
  "Kodo",
  "Koinx",
  "Kong",
  "Kotak Mahindra Bank",
  "Kpmg",
  "KRAFTON India",
  "Kredivo Group",
  "L&T Technology Services",
  "Lancesoft",
  "Leadsquared",
  "Leap",
  "Leapwork",
  "Leena AI",
  "Lemonn, ex - CoinSwitch",
  "Lenskart",
  "Leucine",
  "Levelai",
  "Licious",
  "Limeroadcom",
  "LinkedIn",
  "Livspace",
  "Lognormal Analytics",
  "Longshanks",
  "Loop Health / Loop AI",
  "Lowe'S India",
  "Ltimindtree",
  "Lucidity",
  "Lumber",
  "Lumiq",
  "Macquarie",
  "Magicpin",
  "Mahindra Group",
  "Maiora",
  "MakeMyTrip",
  "Mapmyindia",
  "MAQ Software",
  "Marcus Evans Group",
  "Mars",
  "Marsh",
  "Marvell Technology",
  "Massive Mobility",
  "Mastercard",
  "Mathisys",
  "MathWorks",
  "Mavenir",
  "Mcafee",
  "Mckinsey",
  "Media.net",
  "Mediatek",
  "Medibuddy",
  "Medpace",
  "Medtronic",
  "Meesho",
  "Mercans",
  "Mercari",
  "Mercedes-Benz India",
  "Merkle",
  "Meta",
  "Metroguild",
  "Micron Technology",
  "Microsoft",
  "Milescapital",
  "Millennium",
  "Milliman",
  "Mimecast",
  "Mindtel",
  "Mindtickle",
  "Moengage",
  "MongoDB",
  "Moneyview",
  "Moody'S",
  "Morgan Stanley",
  "Morphe Labs Inc",
  "Morphle",
  "Morquee",
  "Motilal Oswal Financial Services Ltd",
  "Motive",
  "Motorq",
  "Mountblue Technologies",
  "Moveworks",
  "Mpl",
  "Mps Limited",
  "Mrsool",
  "Msci",
  "Msd",
  "Mthree",
  "Mu Sigma",
  "Mudrex",
  "Multiplier",
  "Mycareernet",
  "Mygate",
  "Myhq",
  "MyKaarma",
  "Mynd Solution",
  "Myntra",
  "Mysa",
  "Mysivi",
  "Nagra",
  "Nanonets",
  "Nasdaq",
  "Natwest",
  "Nava",
  "Navi",
  "Nec-Corporation-India",
  "Nected Ai",
  "Neosapien",
  "Nestlé",
  "Netapp",
  "Netomi",
  "Neuralix AI",
  "New Relic",
  "Newgen Softwares",
  "Newton School",
  "Nexturn",
  "Nexus Cognitive",
  "Nference",
  "Nice",
  "Nielsen",
  "Nike",
  "NineLeaps",
  "Nisg",
  "Nissan",
  "Nium",
  "Nk Securities",
  "Nokia",
  "Nomiso",
  "Noumura",
  "Npci",
  "Nse India",
  "Ntt Data",
  "Nutanix",
  "Nvidia",
  "NxtGen Cloud Technologies",
  "Nxtpe",
  "Nykaa",
  "o9 Solutions",
  "Observe Ai",
  "Octagos",
  "Odisoft Technology",
  "Ofbusiness",
  "Officialsubspace",
  "Okta",
  "Ola",
  "OLX",
  "Olyv Smartcoin",
  "Omnissa",
  "Onemg",
  "OneXtel Media",
  "Oneshot.Ai",
  "Onsurity",
  "Opengov Inc.",
  "Opentext",
  "Optimus Info",
  "Optiver",
  "Optum",
  "Oracle",
  "Orange Health",
  "Orbit AI",
  "Origin",
  "Osvi Ai",
  "Out Systems",
  "Outmate",
  "Oyo",
  "Palantir Technologies",
  "Palo Alto Networks",
  "Pando",
  "Park+",
  "Parspec",
  "PayPal",
  "Paytm",
  "PayU",
  "Pearson",
  "Peepalco",
  "Pegasystems",
  "Perforce",
  "Persevex",
  "Pfizer",
  "PharmEasy",
  "Philips",
  "PhonePe",
  "Phonon",
  "PineLabs",
  "Pinnacle Infotech",
  "Pixlie",
  "Planet Spark",
  "PlanEro.in",
  "Playo",
  "PlaySimple Games",
  "Pocket Fm",
  "Pocketful",
  "Pocketpills",
  "Point72",
  "Polestar Analytics",
  "Policybazaar",
  "Poonawalla Fincorp",
  "Porter",
  "Postman",
  "Priceline",
  "Principal Global Services",
  "Prism",
  "Procdna",
  "Procore",
  "Project44",
  "Promptql",
  "PropertyGuru",
  "Prosperr.Io",
  "Providence",
  "Publicis Sapient",
  "Pulse AI",
  "Pw",
  "Pwc",
  "PyjamaHR",
  "Q3 Technologies",
  "Qapita",
  "QiCap.ai",
  "Quadeye",
  "Quadric",
  "Quadstack",
  "Qualcomm",
  "Qualys",
  "Quantbox Trading",
  "Quantiphi",
  "Quickhyre Al",
  "Quillbot",
  "Quince",
  "Quizizz",
  "Quora",
  "Rackspace Technology",
  "Radisys Corporation",
  "Rakuten",
  "Rapidfort",
  "Rapido",
  "Rategain",
  "Razorpay",
  "Recrivio",
  "Recro",
  "Redpin",
  "Redrob",
  "Reliance",
  "Reputation",
  "Resollect",
  "Revolut",
  "Richpanel",
  "Ringcentral",
  "Rippling",
  "Riverbed Technology",
  "Rocket Software",
  "Rocketpay",
  "Rockwell Automation",
  "Roku",
  "Rolls Royce",
  "Rubrik",
  "Rumik",
  "Rupeek",
  "S&P Global",
  "Saas Labs",
  "Sabre",
  "Salary Box",
  "SalesCode.ai",
  "Salesforce",
  "Sambhav",
  "Samsara",
  "Samsung R&D Institute",
  "Sandisk",
  "SAP Labs",
  "Sarvam",
  "Sasken Technologies Limited",
  "Sauce Labs",
  "Scalar Ai Labs",
  "Scaleai",
  "Schrodinger",
  "Scribe",
  "Scripbox",
  "Scry Ai",
  "Seagate Technology",
  "Seiems",
  "Selectorai",
  "Sembly",
  "Sentinelone",
  "Serko",
  "ServiceNow",
  "Shaadi.Com",
  "Sharechat",
  "Shell",
  "Shilpa",
  "Shipbob",
  "Shipsy",
  "Shopify",
  "Siemens",
  "Siemens EDA",
  "Signify",
  "Signity",
  "Signzy",
  "Simplilearn",
  "Simpplr",
  "Singlestore",
  "SiteRecon",
  "Skillovilla",
  "Skillscapital",
  "Slack",
  "SLB",
  "Slice",
  "Slnko Energy",
  "Smallcase",
  "Smart Ims Inc.",
  "Smartsheet",
  "Snaptrude",
  "Snitch",
  "Snowflake",
  "SOAIS",
  "Societe Generale",
  "Solarwind",
  "Solytics Partners",
  "Sophos",
  "Sopra Steria",
  "Sortly",
  "Sourcewiz",
  "SpeakX.ai",
  "Spinny",
  "Spotdraft",
  "Spotnana",
  "Sprinklr",
  "Sprybit",
  "SQUADSTACK",
  "Squarepoint",
  "Srg Buildtech",
  "Stable Money",
  "Standard Chartered",
  "Stanza Living",
  "Staples",
  "Stitch",
  "Stmicroelectronics",
  "Straive",
  "Stratacent",
  "Stripe",
  "Suki",
  "Supermoney",
  "Swiggy",
  "Switch It",
  "Synaptic",
  "Synaptics",
  "Synchrony",
  "Synopsys",
  "Syook",
  "T-Systems Ict India Pvt. Ltd",
  "Tact Ai",
  "Tailored Ai",
  "Talview",
  "Target",
  "Taskus",
  "TBO.COM",
  "TCS (Tata Consultancy Services)",
  "Tech Brains Solutions",
  "Tech Mahindra",
  "Techolution",
  "Teesta",
  "Tejas Networks",
  "Tekion",
  "Teksystems",
  "Tektronix",
  "Tekwissen India",
  "Telus Digital",
  "Teradata",
  "Tesco",
  "Texas Instruments",
  "The Adecco Group",
  "The D. E. Shaw Group",
  "The Trade Desk",
  "Theneo.Io",
  "Thoughtspot",
  "Thoughtworks",
  "Tiket.Com",
  "Times Internet",
  "Timetooth",
  "Titan Company Limited",
  "To The New",
  "Toast",
  "Tower Research Capital",
  "Traact",
  "Traceable (Harness)",
  "Tracelink",
  "Transunion",
  "Travclan",
  "Tredence",
  "Trellix",
  "Trexquant Investment Lp",
  "Trinet",
  "Triology",
  "Truecaller",
  "Truefoundry",
  "Truemeds",
  "Turing",
  "Tuskira",
  "Twilio",
  "Twitter",
  "Uber",
  "Ubs",
  "Udaan",
  "Uipath",
  "UKG",
  "Unacademy",
  "UnifyApps",
  "Unisys",
  "United Airlines",
  "United Breweries Ltd.",
  "Unstop",
  "Unthinkable Solutions",
  "Upstox",
  "Upzenix",
  "Urban Company",
  "Usefulbi",
  "Ustglobal",
  "V-Shesh",
  "Valuefy",
  "Valuelabs",
  "Valura.Ai",
  "Vassar Labs",
  "Vedic Meet",
  "Veeam Software",
  "Veradigm",
  "Versodin",
  "Visa",
  "Viven.ai",
  "Vmware",
  "Vouchagram",
  "Vt Netzwelt",
  "Vyas Edification",
  "Vyapar Apps",
  "Wabtec Corporation",
  "Waferwire Cloud Technologies",
  "Walmart",
  "Warner Bros. Discovery",
  "Wayfair",
  "Weave",
  "Webmd",
  "Wells Fargo",
  "Western Digital",
  "Wework India",
  "Whatfix",
  "Wheelseye",
  "Wicked Ride",
  "Winzo",
  "Wipro",
  "Wise",
  "Wisemonk",
  "Workday",
  "Workindia",
  "Workspan",
  "Worldquant",
  "Worlds",
  "Wpp Media",
  "Writesonic",
  "Wtw",
  "Wyzard.Ai",
  "Xebia",
  "Xilinx",
  "Xoxoday",
  "Xperteez Technology",
  "Yellow.Ai",
  "Yes Bank",
  "Yesmadam",
  "Yugabyte",
  "Zadara",
  "Zaggle",
  "Zamp Ai",
  "Zanskar Tech",
  "Zapcg",
  "Zebra Tech",
  "Zed Mobility",
  "Zemoso Technologies",
  "Zendesk",
  "Zenefits",
  "Zentiti",
  "Zeotap",
  "Zepto",
  "Zerodha",
  "Zeta",
  "Zinnia",
  "Zinnov",
  "ZL Tech",
  "Zoho",
  "Zolve",
  "Zomato",
  "Zoom",
  "Zorvyn",
  "Zs",
  "Zscaler",
  "Zummit Infolabs",
  "Zuora",
  "Zycus",
  "Zynga",
] as const;
